#!/usr/bin/env bash

set -xe
shopt -s globstar nullglob

typeset -A projects
projects=(
	[klipper]=https://github.com/klipper3d/klipper.git 
	[kalico]=https://github.com/KalicoCrew/kalico.git
	[the]=https://github.com/MSzturc/klipper.git
)

if [[ $1 == "--push" ]]; then
	will_push="yes"
else
	will_push=""
fi

if [[ ! -d gitref.git ]]; then
	git init --bare gitref.git
fi
cd gitref.git
for project in "${!projects[@]}"; do
	git fetch "${projects[$project]}" --no-tags --no-write-fetch-head "+refs/heads/*:refs/heads/${project}/*" "+refs/tags/*:refs/tags/${project}/*" "+HEAD:refs/heads/${project}/REMOTE_HEAD"
done
git repack -a -l -d
git pack-refs --all
#tar -cvf ../gitref.git.tar --owner root:0 --group root:0 --format=ustar -- *
