#!/usr/bin/env bash

mkdir image-root
sudo tar -xvf buildroot/output/images/rootfs.tar -C image-root
sudo ./shrink_py
sudo $HOME/vcs/tinyemu-2019-12-21/build_filelist image-root httpfs
rsync -r --delete httpfs/ ../../../web/public/fs/simple.9p/
sudo rm -rf httpfs image-root

